changelog:
  exclude:
    authors: ["dependabot[bot]"]
  categories:
    - title: "✨ New Features"
      labels: ["feature", "enhancement"]
    - title: "🐛 Bug Fixes"
      labels: ["fix", "bug", "bugfix"]
    - title: "⬆️ Dependency Updates"
      dependency_update_patterns: ["all"]
    - title: "📝 Other Changes"
      labels: ["*"]
