name: Android CI/CD

on:
  push:
    branches: ["master"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4

      - name: Checkout Shared Keystore Repository
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v4
        with:
          repository: 'YourGitHubUsername/shared-android-keystore' # <-- 替换为你的！
          ssh-key: ${{ secrets.KEYSTORE_REPO_DEPLOY_KEY }}
          path: 'keystore-repo'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (CI Check)
        if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew build

      - name: Build Release APK
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          CI: "true"
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Create Release Draft
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: app/build/outputs/apk/release/app-release.apk
